/**
 * @file
 * This header file declares the function to create one instance of the TCPFSM state machine.
 * The state machine is configured with a set of function pointers representing the non-default
 * actions and guards of the state machine. Some of these functions may also be declared in
 * this header file in accordance with the configuration of the state machine in the FW Profile
 * Editor. In the latter case, the user has to provide an implementation for these functions
 * in a user-supplied body file.
 *
 * This header file has been automatically generated by the FW Profile Editor.
 * The state machine created by this file is shown in the figure below.
 * @image html TCPFSM.png
 *
 * @author FW Profile code generator version 3.1
 * @date Created on: May 26 2015
 */

/** Make sure to include this header file only once */
#ifndef TCPFSM_H_
#define TCPFSM_H_

/** FW Profile function definitions */
#include "FwProfile/FwSmConstants.h"

/** The identifiers of transition commands (triggers) */
#define PassiveOpen 1
#define ActiveOpen 2
#define ReceiveSyn 3
#define ReceiveAck 4
#define Close 5
#define ReceiveFIN 6
#define CloseExt 7
#define TimerExpire 8

/**
 * Create a new state machine descriptor.
 * This interface creates the state machine descriptor statically.
 * It creates a single static instance of the state machine.
 * The function should only be called once.
 * If it is called several times, it always reconfigures and returns the same instance.
 * @param smData the pointer to the state machine data.
 * A value of NULL is legal (note that the default value of the pointer
 * to the state machine data when the state machine is created is NULL).
 * @return the pointer to the state machine descriptor
 */
FwSmDesc_t TCPFSMCreate(void* smData);

#endif /* TCPFSM_H_ */